---
- name: Deploy Apache Web Server
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy a simple index.html page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>Welcome to Apache!</title></head>
            <body>
              <h1>Hello, World!</h1>
              <p>This is a sample Apache web server deployment using Ansible.</p>
            </body>
          </html>

    - name: Ensure proper file permissions
      file:
        path: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
